//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewYorkDeaths
{
    using System;
    using System.Collections.Generic;
    
    public partial class Death
    {
        public string DeathId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string LeadingCause { get; set; }
        public string Sex { get; set; }
        public string RaceEthnicity { get; set; }
        public Nullable<double> Deaths { get; set; }
        public Nullable<double> DeathRate { get; set; }
        public Nullable<double> AgeAdjustedDeathRate { get; set; }
    }
}
